### PR TITLE
30% of 17 to 16 users. We are late :cry:

### PR DESCRIPTION
**Pull request by jospoortvliet**
@rullzer @blizzz we should get this out... I'm thinking we maybe should go to 100% already but let's be careful for now. But we should go 100% within a week pls, unless big issues are found!

fixes: #269 
Signed-off-by: Jos Poortvliet <jospoortvliet@gmail.com>

### CODE REVIEW

**Comment by jospoortvliet** [comment]
pls wait with mergin, let me add the production channel too.

**Comment by jospoortvliet** [comment]
Ok, added the production channel. Maybe too soon? Can keep it for now, but we should release 16.0.5.1 to it in any case...

**Comment by rullzer** [comment]
This will require fixing the test. I can take a look at that later this week.

**Comment by blizzz** [comment]
I would not put this to production, as at least there is a bug fixing SAML direct login or something. Would consider .1 for it.

**Comment by jospoortvliet** [comment]
Fair enough.

**Comment by jospoortvliet** [comment]
Fair enough.

**Comment by juliushaertl** [comment]
:ping_pong:

**Comment by blizzz** [comment]
needs to be adjusted to current versions

**Comment by jospoortvliet** [comment]
Hmmm, didn't @rullzer just do that in #278 ???

**Comment by jospoortvliet** [comment]
ah no, he didn't, just put 17.0.1 for 17 users... let me try to do this then. Will take me a bit, I'm not so fast :dagger:

**Comment by blizzz** [comment]
> [..] :dagger:

o.O

> “Stars, hide your fires; Let not light see my black and deep desires.” (William Shakespeare, Macbeth )

**Comment by jancborchardt** [comment]
@blizzz my guess: Jos typed `:D` which autocompletes to `:dagger:` on Github … :D

**Comment by blizzz** [comment]
@jancborchardt Sure! See, it's really clever how @jospoortvliet is using the environment to cloak his cravings.

**Pull request closed without merging**
