### PR TITLE
12.0.4 RC3

### PR DESCRIPTION
**Pull request by MorrisJobke**
Signed-off-by: Morris Jobke <hey@morrisjobke.de>

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Blocked by https://github.com/nextcloud/server/issues/7331

**Comment by LukasReschke** [comment]
Still?

**Comment by MorrisJobke** [comment]
> Blocked by nextcloud/server#7331

Nope- Let's merge and ship

**Comment by MorrisJobke** [comment]
Deployed on the updater server.

**Pull request merged**
