### PR TITLE
[prod] 22.2.8, 23.0.5, 24.0.1 + staged rollout to 70%

### PR DESCRIPTION
**Pull request by blizzz**

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Review by AndyScherzinger — APPROVED** [review]

**Comment by nickvergessen** [comment]
Was this deployed? My instance didn't offer me the update so far?

**Comment by mlsxlist** [comment]
Same Herr.

**Comment by blizzz** [comment]
> Was this deployed? My instance didn't offer me the update so far?

apparently not. We had an unclean state, so the automatic git pull did not fetch it. I suspect the hook handler. "Funnily" there are no issues with the test updater server, and the mechanism is the same.

**Comment by blizzz** [comment]
deployed now btw

**Pull request merged**
