### PR TITLE
Put 21 at 30% to 22

### PR DESCRIPTION
**Pull request by skjnldsv**
Signed-off-by: John Molakvoæ (skjnldsv) <skjnldsv@protonmail.com>

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]
LGTM, to be pushed August 9th

**Review by skjnldsv — COMMENTED** [review]
`'20.0.11' => ` should also be adjusted to 20.0.12

**Comment by AndyScherzinger** [comment]
Wait for merge until circles has been fixed

**Comment by skjnldsv** [comment]
Circles migration is good to go then.
We can merge

**Review by blizzz — APPROVED** [review]

**Pull request merged**
