### PR TITLE
25.0.2 RC1, 24.0.8 RC1, 23.0.12 RC1

### PR DESCRIPTION
**Pull request by blizzz**
(the branch is named after the final release date)

### CODE REVIEW

**Comment by blizzz** [comment]
@skjnldsv i also added a commit to try to fetch an `…rc1` build if anything failed. When we have higher RCs in future again, it maybe needs to be made smarter, at least dumbly try higher RCs first :D

**Review by nickvergessen — APPROVED** [review]

**Comment by blizzz** [comment]
25 → 25.0.2RC1 was stuck upgrading photos. Restarted.

**Comment by blizzz** [comment]
Bug in photo's migration, need to rebuild 25 after the fix is in

**Review by skjnldsv — APPROVED** [review]

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/photos/pull/1500

**Pull request merged**
