### PR TITLE
25.0.0 beta 7

### PR DESCRIPTION
**Pull request by blizzz**

### CODE REVIEW

**Comment by blizzz** [comment]
:scream: 

```
Exception: Database error when running migration 20001Date20220830131446 for app photos
An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL
```

**Review by AndyScherzinger — APPROVED** [review]
👍 when the DB migration is fixed

**Comment by ArtificialOwl** [comment]
I got this one myself during fresh installation, not sure it is important:

```
"Table \"oc_photos_collaborators\" has no primary key and therefor will not behave sane in clustered setups. This will throw an exception and not be installable in a future version of Nextcloud."
```

**Comment by PVince81** [comment]
@ArtificialOwl please make another issue in photos and assign Louis. thanks

**Comment by blizzz** [comment]
rebuilt, new tests running

**Comment by blizzz** [comment]
`Column "oc_photos_albums_files"."owner" is NotNull, but has empty string or null as default.` … by Cthulhu

**Comment by blizzz** [comment]
finally

**Pull request merged**
