### PR TITLE
13.0.0 release to 15% of stable channel

### PR DESCRIPTION
**Pull request by MorrisJobke**
* [ ] move 13.0.0 archives from `prereleases` to the `releases` folder on the download server
* [ ] merge this PR
* [ ] deploy this PR to the updater server

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Missing:

* [ ] move files to the `release` folder on the download server
* [ ] merge this PR
* [ ] deploy this PR to the updater server

**Comment by jospoortvliet** [comment]
I can't do step 1 but it'd be nice to get that moving ;-)

**Comment by MorrisJobke** [comment]
Give me two minutes

**Comment by jospoortvliet** [comment]
no hurry

**Comment by MorrisJobke** [comment]
> deploy this PR to the updater server

Let me do this then 10:55 😉

**Comment by MorrisJobke** [comment]
Deployed

**Comment by MorrisJobke** [comment]
@jospoortvliet @NinaNC This was reverted in df4dbb07f5464e893e983b6c2d71af44e8cc2c19 as requested by @nickvergessen due to https://github.com/nextcloud/server/issues/8202

**Comment by MorrisJobke** [comment]
False flag: updater is live again: 10142c6

**Pull request merged**
