### PR TITLE
Bring new major versions to stable channels

### PR DESCRIPTION
**Pull request by MorrisJobke**
Signed-off-by: Morris Jobke <hey@morrisjobke.de>

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Deployed

**Comment by Huster-at-github** [comment]
May I please know what is the exact problem here?

**Comment by MorrisJobke** [comment]
For the maintenance releases we pushed those out on the versions of the stable channel:

11 got 11.0.8
12 got 12.0.6
13 got 13.0.1

This one updates this for the stable channel to:

11 gets 12.0.6
12 gets 13.0.1
13 gets 13.0.1 

That is the normal state of the stable channel. We just went for a short period of time to the other approach.

**Comment by MorrisJobke** [comment]
Could be properly fixed by the sticky stable channel: https://github.com/nextcloud/server/issues/8799

**Comment by dynek** [comment]
Well I updated to 12.0.6 and I still don't see 13 available.

```
Nextcloud Updater - version: v12.0.4RC1

Current version is 12.0.6.

No update available.

Nothing to do.
```

**Comment by MorrisJobke** [comment]
> Well I updated to 12.0.6 and I still don't see 13 available.

Which channel are you on? We only ship this to `stable` and not yet to `production`

**Comment by dynek** [comment]
I was sure I had tried it. Just did and it works. Thank you!

**Comment by ajeoc** [comment]
Is this a bug or correct behaviour?
https://help.nextcloud.com/t/12-0-6-production-channel-offers-13-0-2/31457
I'm not sure but will open an issue if it's a bug.

**Comment by MorrisJobke** [comment]
@ajeoc this is [the correct behavior - 13 is production ready

**Comment by ajeoc** [comment]
@MorrisJobke Thank you!

**Pull request merged**
