### PR TITLE
Fix docs urls

### PR DESCRIPTION
**Pull request by skjnldsv**
Signed-off-by: John Molakvoæ (skjnldsv) <skjnldsv@protonmail.com>

### CODE REVIEW

**Comment by rullzer** [comment]
Update the tests as well please ;)

**Comment by skjnldsv** [comment]
@rullzer I fixed the tests though they were broken before I assume.

**Comment by MorrisJobke** [comment]
Rebased.

**Comment by MorrisJobke** [comment]
> @rullzer I fixed the tests though they were broken before I assume.

I removed them again, as they were fixed on master in a different way.

**Pull request merged**
