### PR TITLE
provide beta of 11.0 via beta channel

### PR DESCRIPTION
**Pull request by MorrisJobke**
This provides the beta on the beta channel.

Deployed on https://updates.nextcloud.com/internal_updater_server/ for testing purposes.

cc @LukasReschke @nickvergessen

### CODE REVIEW

**Comment by nickvergessen** [comment]
tests fail

**Comment by MorrisJobke** [comment]
> tests fail

Fixed

**Comment by MorrisJobke** [comment]
Updates of stable10-daily, 10.0.0, 10.0.1 and 11.0.0beta to 11.0.0beta2 are tested in the updater repo: https://github.com/nextcloud/updater/pull/50/files

**Comment by MorrisJobke** [comment]
This is now deployed on https://updates.nextcloud.com/internal_updater_server/ for testing purposes.

**Comment by MorrisJobke** [comment]
Since 11 hours this is deployed on https://updates.nextcloud.com/updater_server/ and provides the beta.

**Pull request merged**
