### PR TITLE
27.0.0beta1

### PR DESCRIPTION
**Pull request by skjnldsv**

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]

**Review by AndyScherzinger — APPROVED** [review]

**Comment by blizzz** [comment]
no upgrade path from 26.0.1?

**Comment by nickvergessen** [comment]
@skjnldsv the comment above should have been requesting changes i guess

**Comment by blizzz** [comment]
> @skjnldsv the comment above should have been requesting changes i guess

I thought about making that a rejective review, but thought it might have been intentional for unknown reasons, therefore left a simple comment only, to not be a bottle neck in case.

**Comment by skjnldsv** [comment]
> @skjnldsv the comment above should have been requesting changes i guess

https://github.com/nextcloud/updater_server/pull/863 got merged in between :)

**Pull request merged**
