### PR TITLE
Update server improvements

### PR DESCRIPTION
**Pull request by nickvergessen**
Commitwise reviewing is easier.

Tests fail for me locally, but I can't figure out why (even on master), lets see if travis passes

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Okay ... this is tricky. It will fail on current installations because there the updater is still active and shows the button to upgrade. This failed in my two tests yesterday. 😢 I would not provide any update for version 10.0.0 and 9.0.50, 9.0.51, 9.0.52 and 9.0.53 to avoid broken setups. Then we could test this fine granularly and activate the upgrades once we have tested them.

**Comment by LukasReschke** [comment]
@MorrisJobke https://github.com/nextcloud/server/pull/1325/commits/407198245432ce26fd0c2f7ae6ae23be6727600a :-)

**Comment by MorrisJobke** [comment]
Ah ... this is the reason you changed the URL for the update server. If this is deployed on updates.nextcloud.com/update-server only the fixed instances will use this.

Then this is okay 👍

**Comment by MorrisJobke** [comment]
> @MorrisJobke nextcloud/server@4071982 :-) – AKA new endpoint :)

Ah ... and @LukasReschke answered this too :D

**Comment by nickvergessen** [comment]
Yup, that was exactly the idea

**Pull request merged**
