### PR TITLE
Fix missing channel for beta of 11

### PR DESCRIPTION
**Pull request by MorrisJobke**
For https://github.com/nextcloud/server/issues/2385

cc @rullzer @LukasReschke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tests for this are in #18

**Comment by MorrisJobke** [comment]
Currently there are no stable releases for 11 so there is nothing to test here ;)

**Comment by rullzer** [comment]
Fine by me LGTM

**Comment by LukasReschke** [comment]
LGTM

**Pull request merged**
