### PR TITLE
12.0.4 & 11.0.6 on stable/production and 13.0.0 beta 1 on beta

### PR DESCRIPTION
**Pull request by MorrisJobke**
Added what @jospoortvliet requested as well (shipping the beta of 13 via our beta channel).

The zips are not yet in the `releases` folder so this is not deployed anywhere yet. I will add a followup commit to change temporarily the folder to `prereleases` to test on our test update server.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and worked - I will remove the prereleases folder commit and then this is good to be merged once we release those versions.

**Comment by MorrisJobke** [comment]
Deployed.

**Comment by jospoortvliet** [comment]
guys, with this deployed, shouldn't the migration script also work? Ref https://help.nextcloud.com/t/migration-tool-for-owncloud-10-0-2/13769/7 - still not working for that user... Doesn't the ownCloud migrator grab what-to-upgrade from here?

**Comment by MorrisJobke** [comment]
We use https://github.com/nextcloud/owncloud-web-migrator/blob/master/index.php#L411 for this. Let me have a look what is in there.

**Comment by MorrisJobke** [comment]
Updated. Should work now.

**Comment by jospoortvliet** [comment]
So that server offers the right version, too, the migrator-server? There are still questions on the forums, people having trouble upgrading 10.0.3 to Nc, hearing "no suitable candidate available".

**Comment by MorrisJobke** [comment]
> So that server offers the right version, too, the migrator-server? There are still questions on the forums, people having trouble upgrading 10.0.3 to Nc, hearing "no suitable candidate available".

Somebody needs to debug this, but I'm knee-deep into getting 13.0.0 beta 2 out...

**Pull request merged**
